package com.talk;

import java.util.Arrays;
import java.util.List;

public class Constants {
    public static final List<Language> LANGUAGES = Arrays.asList(
        new Language("Afrikaans", "af"),
        new Language("Albanian", "sq"),
        new Language("Amharic", "am"),
        new Language("Arabic", "ar", "ar-SA"),
        new Language("Armenian", "hy"),
        new Language("Assamese", "as"),
        new Language("Aymara", "ay"),
        new Language("Azerbaijani", "az"),
        new Language("Bambara", "bm"),
        new Language("Basque", "eu"),
        new Language("Belarusian", "be"),
        new Language("Bengali", "bn", "bn-BD"),
        new Language("Bhojpuri", "bho"),
        new Language("Bosnian", "bs"),
        new Language("Bulgarian", "bg"),
        new Language("Catalan", "ca"),
        new Language("Cebuano", "ceb"),
        new Language("Chichewa", "ny"),
        new Language("Corsican", "co"),
        new Language("Croatian", "hr"),
        new Language("Czech", "cs"),
        new Language("Danish", "da"),
        new Language("Dhivehi", "dv"),
        new Language("Dogri", "doi"),
        new Language("Dutch", "nl", "nl-NL"),
        new Language("English", "en", "en-US"),
        new Language("Esperanto", "eo"),
        new Language("Estonian", "et"),
        new Language("Ewe", "ee"),
        new Language("Filipino", "tl"),
        new Language("Finnish", "fi"),
        new Language("French", "fr", "fr-FR"),
        new Language("Frisian", "fy"),
        new Language("Galician", "gl"),
        new Language("Georgian", "ka"),
        new Language("German", "de", "de-DE"),
        new Language("Greek", "el", "el-GR"),
        new Language("Guarani", "gn"),
        new Language("Gujarati", "gu"),
        new Language("Haitian Creole", "ht"),
        new Language("Hausa", "ha", "ha-NG"),
        new Language("Hawaiian", "haw"),
        new Language("Hebrew", "iw", "he-IL"),
        new Language("Hindi", "hi", "hi-IN"),
        new Language("Hmong", "hmn"),
        new Language("Hungarian", "hu"),
        new Language("Icelandic", "is"),
        new Language("Igbo", "ig", "ig-NG"),
        new Language("Ilocano", "ilo"),
        new Language("Indonesian", "id", "id-ID"),
        new Language("Irish", "ga"),
        new Language("Italian", "it", "it-IT"),
        new Language("Japanese", "ja", "ja-JP"),
        new Language("Javanese", "jw"),
        new Language("Kannada", "kn"),
        new Language("Kazakh", "kk"),
        new Language("Khmer", "km"),
        new Language("Kinyarwanda", "rw"),
        new Language("Konkani", "gom"),
        new Language("Korean", "ko", "ko-KR"),
        new Language("Krio", "kri"),
        new Language("Kurdish (Kurmanji)", "ku"),
        new Language("Kurdish (Sorani)", "ckb"),
        new Language("Kyrgyz", "ky"),
        new Language("Lao", "lo"),
        new Language("Latin", "la"),
        new Language("Latvian", "lv"),
        new Language("Lingala", "ln"),
        new Language("Lithuanian", "lt"),
        new Language("Luganda", "lg"),
        new Language("Luxembourgish", "lb"),
        new Language("Macedonian", "mk"),
        new Language("Maithili", "mai"),
        new Language("Malagasy", "mg"),
        new Language("Malay", "ms", "ms-MY"),
        new Language("Malayalam", "ml"),
        new Language("Maltese", "mt"),
        new Language("Maori", "mi"),
        new Language("Marathi", "mr"),
        new Language("Mizo", "lus"),
        new Language("Mongolian", "mn"),
        new Language("Myanmar", "my"),
        new Language("Nepali", "ne"),
        new Language("Norwegian", "no"),
        new Language("Odia (Oriya)", "or"),
        new Language("Oromo", "om"),
        new Language("Pashto", "ps"),
        new Language("Persian", "fa", "fa-IR"),
        new Language("Polish", "pl", "pl-PL"),
        new Language("Portuguese", "pt", "pt-PT"),
        new Language("Punjabi", "pa"),
        new Language("Quechua", "qu"),
        new Language("Romanian", "ro"),
        new Language("Russian", "ru", "ru-RU"),
        new Language("Samoan", "sm"),
        new Language("Sanskrit", "sa"),
        new Language("Scots Gaelic", "gd"),
        new Language("Sepedi", "nso"),
        new Language("Serbian", "sr"),
        new Language("Sesotho", "st"),
        new Language("Shona", "sn"),
        new Language("Sindhi", "sd"),
        new Language("Sinhala", "si"),
        new Language("Slovak", "sk"),
        new Language("Slovenian", "sl"),
        new Language("Somali", "so"),
        new Language("Spanish", "es", "es-ES"),
        new Language("Sundanese", "su"),
        new Language("Swahili", "sw", "sw-KE"),
        new Language("Swedish", "sv"),
        new Language("Tajik", "tg"),
        new Language("Tamil", "ta", "ta-IN"),
        new Language("Tatar", "tt"),
        new Language("Telugu", "te"),
        new Language("Thai", "th", "th-TH"),
        new Language("Tigrinya", "ti"),
        new Language("Tsonga", "ts"),
        new Language("Turkish", "tr", "tr-TR"),
        new Language("Turkmen", "tk"),
        new Language("Twi", "ak"),
        new Language("Ukrainian", "uk"),
        new Language("Urdu", "ur", "ur-PK"),
        new Language("Uyghur", "ug"),
        new Language("Uzbek", "uz"),
        new Language("Vietnamese", "vi", "vi-VN"),
        new Language("Welsh", "cy"),
        new Language("Xhosa", "xh"),
        new Language("Yiddish", "yi"),
        new Language("Yoruba", "yo", "yo-NG"),
        new Language("Zulu", "zu")
    );

    public static final String TRANSLATION_API_URL = "https://translate.googleapis.com/translate_a/single";
}